# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person'),
        ),
    ]
